import { AuthService } from "../../src/services/AuthService";
import { QRService } from "../../src/services/QRService";
import { ReminderService } from "../../src/services/ReminderService";

// ─── Stub the cache so unit tests don't need Redis ──────────────────────────
jest.mock("../../src/cache/redisClient", () => ({
  cache: {
    getOrSet: async (_key: string, factory: () => Promise<unknown>) => factory(),
    set: jest.fn(),
    get: jest.fn().mockResolvedValue(null),
    del: jest.fn(),
  },
  redisClient: { on: jest.fn() },
}));

// ═══════════════════════════════════════════════════════════════════════════════
// AuthService
// ═══════════════════════════════════════════════════════════════════════════════
describe("AuthService", () => {
  beforeEach(() => {
    // Reset the in-memory DB between tests by re-importing (simple approach)
    jest.resetModules();
  });

  it("should register a user and return public fields (no passwordHash)", async () => {
    const user = await AuthService.register({
      email: "alice@example.com",
      password: "secret123",
      name: "Alice",
      role: "creator",
    });

    expect(user.email).toBe("alice@example.com");
    expect(user.name).toBe("Alice");
    expect(user.role).toBe("creator");
    expect(user.id).toBeDefined();
    expect((user as any).passwordHash).toBeUndefined();
  });

  it("should reject duplicate email on registration", async () => {
    await AuthService.register({
      email: "bob@example.com",
      password: "pass123",
      name: "Bob",
      role: "eventee",
    });

    await expect(
      AuthService.register({
        email: "bob@example.com",
        password: "other",
        name: "Bob Again",
        role: "eventee",
      })
    ).rejects.toThrow("already exists");
  });

  it("should login with correct credentials and return tokens", async () => {
    await AuthService.register({
      email: "charlie@example.com",
      password: "mypassword",
      name: "Charlie",
      role: "creator",
    });

    const { user, tokens } = await AuthService.login({
      email: "charlie@example.com",
      password: "mypassword",
    });

    expect(user.email).toBe("charlie@example.com");
    expect(tokens.accessToken).toBeDefined();
    expect(tokens.refreshToken).toBeDefined();
    expect(typeof tokens.accessToken).toBe("string");
    expect(tokens.accessToken.split(".")).toHaveLength(3); // valid JWT structure
  });

  it("should reject login with wrong password", async () => {
    await AuthService.register({
      email: "dave@example.com",
      password: "correct",
      name: "Dave",
      role: "eventee",
    });

    await expect(
      AuthService.login({ email: "dave@example.com", password: "wrong" })
    ).rejects.toThrow("Invalid email or password");
  });

  it("should reject login with unknown email", async () => {
    await expect(
      AuthService.login({ email: "nobody@example.com", password: "x" })
    ).rejects.toThrow("Invalid email or password");
  });

  it("should generate a valid refresh token that can be exchanged for an access token", async () => {
    await AuthService.register({
      email: "eve@example.com",
      password: "password1",
      name: "Eve",
      role: "creator",
    });

    const { tokens } = await AuthService.login({
      email: "eve@example.com",
      password: "password1",
    });

    const result = await AuthService.refreshToken(tokens.refreshToken);
    expect(result.accessToken).toBeDefined();
    expect(result.accessToken.split(".")).toHaveLength(3);
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// QRService
// ═══════════════════════════════════════════════════════════════════════════════
describe("QRService", () => {
  it("should generate a signed token and a data URI", async () => {
    const { token, dataUri } = await QRService.generate("ticket-123", "event-456");

    expect(token).toBeDefined();
    expect(typeof token).toBe("string");
    expect(token.split(".")).toHaveLength(2); // payload.signature
    expect(dataUri).toMatch(/^data:image\/png;base64,/);
  });

  it("should verify a token generated by generate()", async () => {
    const { token } = await QRService.generate("ticket-abc", "event-def");
    const payload = QRService.verify(token);

    expect(payload.ticketId).toBe("ticket-abc");
    expect(payload.eventId).toBe("event-def");
    expect(payload.issuedAt).toBeLessThanOrEqual(Math.floor(Date.now() / 1000));
  });

  it("should reject a tampered token (modified payload)", () => {
    // Manually craft a token with a bad signature
    const fakePayload = Buffer.from(JSON.stringify({ ticketId: "hacked", eventId: "x", issuedAt: 0 })).toString("base64url");
    const fakeToken = `${fakePayload}.invalidsignature`;

    expect(() => QRService.verify(fakeToken)).toThrow("Invalid or tampered QR token");
  });

  it("should reject a completely garbage string", () => {
    expect(() => QRService.verify("not.a.valid.token")).toThrow("Invalid or tampered QR token");
  });

  it("should reject an empty string", () => {
    expect(() => QRService.verify("")).toThrow("Invalid or tampered QR token");
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// ReminderService — computeRemindAt
// ═══════════════════════════════════════════════════════════════════════════════
describe("ReminderService.computeRemindAt", () => {
  const eventDate = new Date("2026-06-15T18:00:00.000Z");

  it("should compute 1 hour before the event", () => {
    const result = ReminderService.computeRemindAt(eventDate, { unit: "hour", value: 1 });
    const expected = new Date("2026-06-15T17:00:00.000Z");
    expect(result.getTime()).toBe(expected.getTime());
  });

  it("should compute 2 hours before the event", () => {
    const result = ReminderService.computeRemindAt(eventDate, { unit: "hour", value: 2 });
    const expected = new Date("2026-06-15T16:00:00.000Z");
    expect(result.getTime()).toBe(expected.getTime());
  });

  it("should compute 1 day before the event", () => {
    const result = ReminderService.computeRemindAt(eventDate, { unit: "day", value: 1 });
    const expected = new Date("2026-06-14T18:00:00.000Z");
    expect(result.getTime()).toBe(expected.getTime());
  });

  it("should compute 3 days before the event", () => {
    const result = ReminderService.computeRemindAt(eventDate, { unit: "day", value: 3 });
    const expected = new Date("2026-06-12T18:00:00.000Z");
    expect(result.getTime()).toBe(expected.getTime());
  });

  it("should compute 1 week before the event", () => {
    const result = ReminderService.computeRemindAt(eventDate, { unit: "week", value: 1 });
    const expected = new Date("2026-06-08T18:00:00.000Z");
    expect(result.getTime()).toBe(expected.getTime());
  });

  it("should compute 2 weeks before the event", () => {
    const result = ReminderService.computeRemindAt(eventDate, { unit: "week", value: 2 });
    const expected = new Date("2026-06-01T18:00:00.000Z");
    expect(result.getTime()).toBe(expected.getTime());
  });
});